<form action="search">

    <input type="text" name="q"/>
    <input type="submit" value="search"/>
</form>
<?php if($this->query){
    foreach ($this->matches as $match){
        $doc = $match->getDocument();
        echo "<li class=\"searchresults\"><a href=\"$match->url\">";
        foreach ($doc->getFieldNames() as $name){
            echo '<b>'.$name .':</b> ' .$this->query->highlightMatches($doc->getFieldValue($name)).': ';
        }
        echo "</a></li><br/>";
    }
} else {
    echo 'add q to url';
}

?>