<dl>
    <?php foreach ($this->pv as $entry): ?>
    <dt><?php echo $this->escape($entry->idPV) ?></dt>
    <dd><?php 
	$row = $entry->findDependentRowset('Default_Model_Value')->current();
	if ($row) {
		echo $this->escape($row->Value);
	}
 ?></dd>
    <dd><?php 
	$row = $entry->findDependentRowset('Default_Model_ValueMeaning')->current();
	if ($row) {
		echo $this->escape($row->Meaning);
	}
 ?></dd>
    <?php endforeach ?>
</dl>
