<?php

echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>  
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
  <title>ISO11179</title>
  <? $this->headLink()->appendStylesheet($this->baseUrl().'/css/main.css'); ?>
  <? $this->headLink()->appendStylesheet($this->baseUrl().'/css/screen.css', 'screen, projection'); ?>
  <? $this->headLink()->appendStylesheet($this->baseUrl().'/css/ie.css', 'screen, projection', 'IE'); ?>
  <? $this->headLink()->appendStylesheet($this->baseUrl().'/css/print.css', 'print'); ?>
  <?= $this->headlink(); ?>
</head> 
<body>
<? $this->render('header.phtml') ?>
<div id="content" class='container'>
	<div class='span-5 navigation'>
		<?= $this->navigation()->menu(); ?>
	</div>
	<div class='span-18 maincontent'>
		<?= $this->layout()->content ?>		
	</div>
</div>
<? $this->render('footer.phtml') ?>
</body>
</html>
