<table>
	<caption class="loud"><?= $this->caption  ?></caption>
	<tr><thead>
		<?php
		$value = $this->data[0];
			foreach ($value as $key => $value) {
				echo "<th>".$key."</th>";}
		?>
	</tr></thead>
	
		<?php
		$x=0;
		foreach ($this->data as $key => $value) {
			echo "<tr".($x++%2?" class=\"even\">":">");
			$i=0;
			foreach ($value as $key => $value) {
				echo "<td>";
				if (!$i++) {
					echo '<a href="'.$this->editURL.'/id/'.$value.'">'.$value.'</a>';
				} else echo $value;
				echo "</td>";
			}
			echo "</tr>";
		}
		?>
</table>